import _ from 'lodash'

export const types = {
    topType: {
        NoHair: 'Glatze',
        Eyepatch: 'Augenklappe',
        Hat: 'Hut',
        Hijab: 'Hijab',
        Turban: 'Turban',
        WinterHat1: 'Mütze',
        WinterHat2: 'Mütze mit Bommel',
        WinterHat3: 'Weihnachtsmütze',
        WinterHat4: 'Mütze mit Ohren',
        LongHairBigHair: 'Langes Haar',
        LongHairBob: 'Bob',
        LongHairBun: 'Dutt',
        LongHairCurly: 'Lockig',
        LongHairCurvy: 'Wellig',
        LongHairDreads: 'Dreadlocks',
        LongHairFrida: 'Blumen',
        LongHairFro: 'Afro',
        LongHairFroBand: 'Afro mit Band',
        LongHairNotTooLong: 'Mittellanges Haar',
        LongHairShavedSides: 'Langes Haar mit Sidecut',
        LongHairMiaWallace: 'Mittellanges Haar mit Pony',
        LongHairStraight: 'Gardinenhaar',
        LongHairStraight2: 'Lange gerade Haar',
        LongHairStraightStrand: 'Langes Haar mit Strähnen',
        ShortHairDreads01: 'Kurze Dreads mit Sidecut',
        ShortHairDreads02: 'Kurze Dreads',
        ShortHairFrizzle: 'Softeis',
        ShortHairShaggyMullet: 'Vokuhila',
        ShortHairShortCurly: 'Lockiger Pony',
        ShortHairShortFlat: 'Fassonschnitt',
        ShortHairShortRound: 'Kurze Haare',
        ShortHairShortWaved: 'Leichte Tolle',
        ShortHairSides: 'Kranz',
        ShortHairTheCaesar: 'Caesar',
        ShortHairTheCaesarSidePart: 'Caesar mit Line-Up',
    },
    facialHairType: {
        Blank: '',
        BeardMedium: '',
        BeardLight: '',
        BeardMagestic: '',
        MoustacheFancy: '',
        MoustacheMagnum: '',
    },
    clotheType: {
        BlazerShirt: '',
        BlazerSweater: '',
        CollarSweater: '',
        GraphicShirt: '',
        Hoodie: '',
        Overall: '',
        ShirtCrewNeck: '',
        ShirtScoopNeck: '',
        ShirtVNeck: '',
    },
    skinColor: {
        Tanned: '',
        Yellow: '',
        Pale: '',
        Light: '',
        Brown: '',
        DarkBrown: '',
        Black: '',
    },
    eyeType: {
        Close: '',
        Cry: '',
        Default: '',
        Dizzy: '',
        EyeRoll: '',
        Happy: '',
        Hearts: '',
        Side: '',
        Squint: '',
        Surprised: '',
        Wink: '',
        WinkWacky: '',
    },
    facialHairColor: {
        Auburn: '',
        Black: '',
        Blonde: '',
        BlondeGolden: '',
        Brown: '',
        BrownDark: '',
        Platinum: '',
        Red: '',
    },
    accessoriesType: {
        Blank: '',
        Kurt: '',
        Prescription01: '',
        Prescription02: '',
        Round: '',
        Sunglasses: '',
        Wayfarers: '',
    },
    hatColor: {
        Black: '',
        Blue01: '',
        Blue02: '',
        Blue03: '',
        Gray01: '',
        Gray02: '',
        Heather: '',
        PastelBlue: '',
        PastelGreen: '',
        PastelOrange: '',
        PastelRed: '',
        PastelYellow: '',
        Pink: '',
        Red: '',
        White: '',
    },
}

export const get = type => {
    return Object.keys(types[type]).map(t => ({
        key: t,
        value: t,
        text: types[type][t] === '' ? t : types[type][t],
    }))
}

export const rand = type => {
    return Object.keys(types[type])[_.random(0, Object.keys(types[type]).length - 1)]
}
